; Name: Sophia Liu 
; Name of program: Converts.inc, Conversion constants 
; Function of program: Contains constants used in converts.asm for 
;                      Dec2String and Hex2String functions 
; Table of contents: 
;     contains constants ASCII_NULL and A_OFFSET 
; Revision history: 
;     10/14/16 Sophia Liu    Created file and added constants 
;     10/15/16 Sophia Liu    Updated comments      


ASCII_NULL EQU 0  ; ASCII null character
A_OFFSET EQU 10   ; offset to correctly convert to ASCII characters A-F