;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                   EventQ.inc                               ;
;                             Event Queue Constants                          ;
;                                   EE/CS 51                                 ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Description: This file contains the definitions for constants for the
;              EventQueue functions
;
; Revision History:
;     12/02/2016 Sophia Liu    initial revision

NO_CRITICAL_ERROR   EQU 0    ; critical error flag value if no critical error
CRITICAL_ERROR      EQU 1    ; critical error flag value if there is a critical error
